"""create graph_state_records table

Revision ID: e049165df0df
Revises: 
Create Date: 2025-04-28 15:21:19.102706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e049165df0df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_state_records',
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('state_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_index(op.f('ix_graph_state_records_thread_id'), 'graph_state_records', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_state_records_thread_id'), table_name='graph_state_records')
    op.drop_table('graph_state_records')
    # ### end Alembic commands ###
